import styles from '@/app/globals.css';
import SideNavBar from '../components/sideNavBar.component/sideNavBar';
import { Providers } from "../providers.jsx";

export const metadata = {
  title: 'Tutora.IA',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Providers>
          <SideNavBar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}